name: Release Tag
run-name: "${{ github.event_name }}: Release (${{ github.ref_name }})"

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  tag-version:
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'release/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Extract version from release branch name
        id: extract_version
        run: |
          RELEASE_BRANCH="${{ github.event.pull_request.head.ref }}"
          VERSION="${RELEASE_BRANCH#release/}"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Create Git Tag
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          TAG="v${{ steps.extract_version.outputs.version }}"
          git tag -a "$TAG" -m "Release ${{ steps.extract_version.outputs.version }}"
          git push https://x-access-token:${GH_TOKEN}@github.com/adrian-bialy/trading-data-warehouse.git "$TAG"
